// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: bbfzaxcdeybjvrydevgb

class SupabaseConfig {
  static const String supabaseUrl = 'https://bbfzaxcdeybjvrydevgb.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJiZnpheGNkZXlianZyeWRldmdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM2NTg1MTEsImV4cCI6MjA3OTIzNDUxMX0._pgBdjdvDx5zqccow9aV9u9swHaTG9E6AClhyaUS5Fs';
}
